### ISSUE TITLE
Block css gets compiled wrong

### ISSUE THREAD

**Issue by Ktarnaj** [Jaspero/schema-forms#109]
CSS that has the option for multiple values gets compiled wrong, for example:
If I write 'margin: 0 auto' in the block's SCSS component it gets converted to 'margin: 0auto' on web which results in nothing being applied. The same thing occurs when trying to add multiple values with padding (ex. 'padding: 0 10px' --> 'padding: 010px' which also results in nothing being applied).

<img width="162" alt="Screenshot 2022-05-31 at 11 01 05" src="https://user-images.githubusercontent.com/53821396/171135697-514ebc0f-1da5-4427-a284-772bb1a1edc3.png">

<img width="142" alt="Screenshot 2022-05-31 at 11 01 39" src="https://user-images.githubusercontent.com/53821396/171135814-0dc4a993-7e99-40de-ae4f-3d5c402718a5.png">

**Comment by flauc** [comment]
closed by https://github.com/Jaspero/schema-forms/commit/fc712015addbf0817ee3f9ca0d0adaa6e08f1624
