### ISSUE TITLE
RefComponent improvements

### ISSUE THREAD

**Issue by flauc** [Jaspero/schema-forms#54]
We need to make a few quality of life improvements here. 

- [x] Clicking on an item in the table should close the dialog (maybe we add a configuration option `closeOnSelect` which defaults to true?)
- [x] The Search along with the table header should be fixed and only the rows should be scrollable
![image](https://user-images.githubusercontent.com/4489834/121883559-2a6faf80-cd12-11eb-8e3e-abbdcc34517d.png)
- [x] Clicking "Apply Value" should also close the dialog
- [x] Just for consistency clear should be a matSuffix so that the inputs are the same length
![image](https://user-images.githubusercontent.com/4489834/121883824-80445780-cd12-11eb-940e-4b7c62039fd7.png)

**Comment by AntonioStipic** [comment]
'Clear' button doesn't reset searchControl

**Comment by AntonioStipic** [comment]
#55
