### ISSUE TITLE
Inline Editor Remove

### ISSUE THREAD

**Issue by iGrubesic** [Jaspero/schema-forms#79]
This is a strange one, removing elements seems to work perfectly in development but doesn't in production.

**Comment by flauc** [comment]
This is now somewhat fixed and I'll close it.
If you now delete a segment with the inline editor it will be removed when saved. However if you close and re-open the page builder you'll still see the deleted segment. Furthermore if you then edit the content, the edited not deleted content is what will be persisted on save.
