### ISSUE TITLE
Ref Table Multi Select

### ISSUE THREAD

**Issue by flauc** [Jaspero/schema-forms#86]
We need to add a new component that is very similar to the ref table component we already have. The main difference being the option to select multiple items.

**Comment by flauc** [comment]
My thinking is that the difference between single select and multi select is justification enough for having two different components.

**Comment by AntonioStipic** [comment]
As we have discussed, this has already been implemented in ref component via "multiple" option.

Docs for future reference: https://docs.jaspero.co/docs/fields/ref
